esphome:
  name: mbr_blind_controller

<<: !include ../common/common.yaml

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret mbr_blinds_ota

ota:
  password: !secret mbr_blinds_ota

output:
  - platform: gpio
    pin: D1
    id: left_button_up
  - platform: gpio
    pin: D2
    id: left_button_stop
  - platform: gpio
    pin: D3
    id: left_button_down  
  - platform: gpio
    pin: D5
    id: right_button_up
  - platform: gpio
    pin: D6
    id: right_button_stop
  - platform: gpio
    pin: D7
    id: right_button_down  

button:
  - platform: template
    name: "Blinds Up"
    id: bu_button
    on_press: 
      then:
        - output.turn_on: left_button_up
        - delay: 350ms
        - output.turn_off: left_button_up
        - output.turn_on: right_button_up
        - delay: 350ms
        - output.turn_off: right_button_up 

  - platform: template
    name: "Blinds Stop"
    id: bs_button
    on_press: 
      then:
        - output.turn_on: left_button_stop
        - delay: 350ms
        - output.turn_off: left_button_stop
        - output.turn_on: right_button_up
        - delay: 350ms
        - output.turn_off: right_button_stop 
  - platform: template
    name: "Blinds Down"
    id: bd_button
    on_press: 
      then:
        - output.turn_on: left_button_down
        - delay: 350ms
        - output.turn_off: left_button_down
        - output.turn_on: right_button_down
        - delay: 350ms
        - output.turn_off: right_button_down     
    